# Generated by Django 4.2.6 on 2023-10-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedication',
            name='prescribed_medications_prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='purrfectcareview.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescriptions_patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='purrfectcareview.patient'),
        ),
    ]
