# Generated by Django 4.2.6 on 2023-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0002_alter_prescribedmedication_prescribed_medications_prescription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_name',
            field=models.CharField(max_length=50),
        ),
    ]
