# Generated by Django 4.2.6 on 2023-11-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0005_alter_clinic_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patients_clinic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purrfectcareview.clinic'),
            preserve_default=False,
        ),
    ]
