# Generated by Django 4.2.6 on 2023-11-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0006_patient_patients_clinic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescriptions_employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purrfectcareview.employee'),
            preserve_default=False,
        ),
    ]
