# Generated by Django 4.2.6 on 2023-12-02 15:59

from django.db import migrations, models
import purrfectcareview.models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0007_prescription_prescriptions_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_photo',
            field=models.ImageField(default='profile_pictures/default.png', upload_to=purrfectcareview.models.upload_to_profile_pictures, verbose_name='Image'),
        ),
    ]
