# Generated by Django 4.2.6 on 2023-12-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0009_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('cancelled', 'Cancelled'), ('complete', 'Complete')], max_length=30),
        ),
    ]
