# Generated by Django 4.2.5 on 2023-12-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0010_alter_visit_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_status',
            field=models.CharField(choices=[('Zaplanowana', 'zaplanowana'), ('Odwołana', 'odwołana'), ('Zakończona', 'zakończona')], max_length=30),
        ),
    ]
