# Generated by Django 4.2.6 on 2023-12-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0011_alter_visit_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_gender',
            field=models.CharField(choices=[('samiec', 'Samiec'), ('samica', 'Samica')], max_length=6),
        ),
    ]
