# Generated by Django 4.2.5 on 2023-12-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0012_alter_patient_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_name',
        ),
    ]
