# Generated by Django 4.2.6 on 2023-12-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0012_alter_patient_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedication',
            name='medication_dosage',
            field=models.TextField(default='1 tabletka dziennie'),
            preserve_default=False,
        ),
    ]
