# Generated by Django 4.2.6 on 2023-12-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0013_prescribedmedication_medication_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedication',
            name='medication_dosage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
