# Generated by Django 4.2.5 on 2023-12-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0013_remove_photo_photo_name'),
        ('purrfectcareview', '0014_alter_prescribedmedication_medication_dosage'),
    ]

    operations = [
    ]
