# Generated by Django 4.2.5 on 2023-12-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0015_merge_20231214_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patients_clinic_id',
        ),
        migrations.AddField(
            model_name='visit',
            name='visits_clinic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purrfectcareview.clinic'),
        ),
    ]
