# Generated by Django 4.2.6 on 2024-01-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfectcareview', '0016_remove_patient_patients_clinic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employees_clinic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purrfectcareview.clinic'),
        ),
    ]
